// Robinhood Network Switcher Hook
// Generated by [N]skills - https://www.nskills.xyz

'use client';

import { useCallback, useMemo } from 'react';
import { useChainId, useSwitchChain } from 'wagmi';
import { robinhoodTestnet } from '../lib/chains';

export type RobinhoodNetwork = 'testnet';

export function useRobinhoodNetwork() {
  const chainId = useChainId();
  const { switchChain, isPending, error } = useSwitchChain();

  const currentNetwork = useMemo((): RobinhoodNetwork | null => {
    if (chainId === 46630) return 'testnet';
    return null;
  }, [chainId]);

  const isOnRobinhood = currentNetwork !== null;

  const switchToRobinhood = useCallback(
    async () => {
      await switchChain({ chainId: robinhoodTestnet.id });
    },
    [switchChain]
  );

  return {
    currentNetwork,
    isOnRobinhood,
    isSwitching: isPending,
    switchError: error,
    switchToRobinhood,
    chainId,
  };
}

export function getRobinhoodExplorerUrl(txHash: string): string {
  return `https://explorer.testnet.chain.robinhood.com/tx/${txHash}`;
}

export function getRobinhoodAddressUrl(address: string): string {
  return `https://explorer.testnet.chain.robinhood.com/address/${address}`;
}