// Robinhood Chain Deploy Script
// Generated by [N]skills - https://www.nskills.xyz

import hre from "hardhat";

async function main() {
  const [deployer] = await hre.ethers.getSigners();
  console.log("Deploying with account:", deployer.address);

  const HelloRobinhood = await hre.ethers.getContractFactory("HelloRobinhood");
  const contract = await HelloRobinhood.deploy();
  await contract.waitForDeployment();

  const address = await contract.getAddress();
  console.log("HelloRobinhood deployed to:", address);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});