// Robinhood Chain Testnet Configuration
// Generated by [N]skills - https://www.nskills.xyz

import { defineChain } from 'viem';

/**
 * Robinhood Chain Testnet (Chain ID: 46630)
 * Arbitrum Orbit L2 with ETH as native gas token
 */
export const robinhoodTestnet = defineChain({
  id: 46630,
  name: 'Robinhood Chain Testnet',
  nativeCurrency: {
    name: 'ETH',
    symbol: 'ETH',
    decimals: 18,
  },
  rpcUrls: {
    default: {
      http: ['https://rpc.testnet.chain.robinhood.com'],
      webSocket: ['wss://feed.testnet.chain.robinhood.com'],
    },
    public: {
      http: ['https://rpc.testnet.chain.robinhood.com'],
      webSocket: ['wss://feed.testnet.chain.robinhood.com'],
    },
  },
  blockExplorers: {
    default: {
      name: 'Robinhood Explorer',
      url: 'https://explorer.testnet.chain.robinhood.com',
    },
  },
  testnet: true,
});

export const robinhoodChains = [robinhoodTestnet] as const;
export type RobinhoodChainId = 46630;