// Robinhood Chain Contract Addresses
// Generated by [N]skills - https://www.nskills.xyz
// Source: Official Robinhood Chain documentation

import type { Address } from 'viem';

/**
 * Robinhood Chain Testnet (L2) Contract Addresses
 */
export const ROBINHOOD_TESTNET_CONTRACTS = {
  // Token contracts
  WETH: '0x7943e237c7F95DA44E0301572D358911207852Fa' as Address,
  TSLA: '0xC9f9c86933092BbbfFF3CCb4b105A4A94bf3Bd4E' as Address,
  AMZN: '0x5884aD2f920c162CFBbACc88C9C51AA75eC09E02' as Address,
  PLTR: '0x1FBE1a0e43594b3455993B5dE5Fd0A7A266298d0' as Address,
  NFLX: '0x3b8262A63d25f0477c4DDE23F83cfe22Cb768C93' as Address,
  AMD: '0x71178BAc73cBeb415514eB542a8995b82669778d' as Address,

  // L2 bridge and gateways
  L2_GATEWAY_ROUTER: '0x77bF00A6A90c600f214b34BAFBB7918c0cF113A8' as Address,
  L2_ERC20_GATEWAY: '0x8689aFB9086734e12beA6b5DF541a1da252Ea32a' as Address,
  L2_WETH_GATEWAY: '0x5A8F55202A625D12FFCb76F857FE4563bC8Ce413' as Address,
  L2_WETH: '0x7943e237c7F95DA44E0301572D358911207852Fa' as Address,
  L2_PROXY_ADMIN: '0xE743e696B00789Ef489cF617477771764E9283a0' as Address,

  // Misc
  L2_MULTICALL: '0xa432504b6F04Cafe775b09D8AA92e8dbe41Ec7a8' as Address,
} as const;

export const ROBINHOOD_CONFIG = {
  testnet: {
    chainId: 46630,
    name: 'Robinhood Chain Testnet',
    rpcUrl: 'https://rpc.testnet.chain.robinhood.com',
    wsUrl: 'wss://feed.testnet.chain.robinhood.com',
    explorerUrl: 'https://explorer.testnet.chain.robinhood.com',
  },
} as const;