// Robinhood Wagmi Configuration
// Generated by [N]skills - https://www.nskills.xyz

import { http, webSocket } from 'wagmi';
import { robinhoodTestnet } from './chains';

export const robinhoodTransports = {
  [robinhoodTestnet.id]: webSocket('wss://feed.testnet.chain.robinhood.com'),
} as const;

export const robinhoodChainsConfig = [robinhoodTestnet] as const;