// Robinhood Chain Hardhat Network Config
// Generated by [N]skills - https://www.nskills.xyz

const config = {
  robinhood: {
    url: "https://rpc.testnet.chain.robinhood.com",
    accounts: process.env.PRIVATE_KEY ? [process.env.PRIVATE_KEY] : [],
    chainId: 46630,
  },
};

export default config;